### ISSUE TITLE
Update to fix issues with some evergreen browsers

### ISSUE THREAD

**Issue by swederik** [clinical-meteor/router-middleware-stack#1]
Hi Abigail,

Could you pull the latest from the Iron meteor middleware stack? It appears that routing is broken on a few browsers, including Chrome.

See: https://github.com/iron-meteor/iron-router/issues/1513

Thanks!

**Comment by swederik** [comment]
Thanks!

**Comment by awatson1978** [comment]
Yup!
Just published as `2.1.2`.  Haven't updated other libraries that rely on `clinical:router-middleware-stack` as a dependency, but happy to accept pull requests and republish other packages as needed.
